# Generated by Django 3.1.3 on 2020-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='发票号码')),
                ('description', models.CharField(max_length=100, verbose_name='开票内容')),
                ('create_date', models.DateField(verbose_name='开票日期')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名')),
                ('company_id', models.CharField(max_length=100, verbose_name='税号')),
                ('price', models.FloatField(verbose_name='发票金额')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('category', models.CharField(choices=[('交通费', '交通费'), ('餐饮费', '餐饮费'), ('未选择', '未选择')], default='未选择',
                                              max_length=100, verbose_name='发票类型')),
            ],
        ),
    ]
